name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag sandeepraj0105/dockerimage-automate:latest
    - name: push the Docker image
      run: docker login -u sandeepraj0105 -p ${{sectres.DOCKER_TOKEN }} && docker push sandeepraj0105/dockerimage-automate:latest
